services:
  postgresql:
    container_name: postgresql_catalogo
    image: postgres:15.4-bullseye
    restart: always

    environment:
      POSTGRES_PASSWORD: juli2004
      POSTGRES_DB: catalogo_db_dev
      POSTGRES_USER: julieta
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5438:5432"

    volumes:
      # es buena practica path relativo desde el proyecto ./_data:/var/lib/postgresql
      - ./_data:/var/lib/postgresql/data
    networks:
      - mired

  pg-admin:
    container_name: pgadmin4_container_catalogo
    image: dpage/pgadmin4:8
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: chakijulieta@gmail.com
      PGADMIN_DEFAULT_PASSWORD: juli2004
    ports:
      - "5050:80"
    networks:
      - mired

networks:
  mired:
    driver: bridge